### ISSUE TITLE
Support for Media and Brightness keys

### ISSUE THREAD

**Issue by danielcherubini** [dakyskye/dxhd#13]
Hi I'm having issues, these keys don't seem to be supported

```## Media Keys
#XF86AudioMute
$HOME/dotfiles/utils/volume.sh mute
#XF86AudioRaiseVolume
$HOME/dotfiles/utils/volume.sh up
#XF86AudioLowerVolume
$HOME/dotfiles/utils/volume.sh down

#XF86MonBrightnessUp
$HOME/dotfiles/utils/brightness.sh up
#XF86MonBrightnessDown
$HOME/dotfiles/utils/brightness.sh down```

**Comment by dakyskye** [comment]
Thanks for opening the issue, I will look into XGB source, and transpile those keys.

**Comment by dakyskye** [comment]
They seem to be defined https://github.com/BurntSushi/xgbutil/blob/master/keybind/keysymdef.go#L2103

What does `dxhd -d` output for you?

**Comment by danielcherubini** [comment]
```binding: xf86audiomute
action:
$HOME/dotfiles/utils/volume.sh mute

binding: xf86audioraisevolume
action:
$HOME/dotfiles/utils/volume.sh up

binding: xf86audiolowervolume
action:
$HOME/dotfiles/utils/volume.sh down

binding: xf86monbrightnessup
action:
$HOME/dotfiles/utils/brightness.sh up

binding: xf86monbrightnessdown
action:
$HOME/dotfiles/utils/brightness.sh down
```

looks fine till i run dxhd and get this error message

```{"level":"fatal","ts":"2020-06-15T17:46:40.153+0200","caller":"dxhd-git/main.go:186","msg":"can not register a keybinding","keybinding":"xf86audiomute","error":"Could not find a valid keycode in the string 'xf86audiomute'. Key binding failed."}```

**Comment by dakyskye** [comment]
All right, thanks, I will fix this ASAP.

**Comment by dakyskye** [comment]
Alright, found the issue! XF86 keys have to be case-sensitive.  It'll be fixed soon.

**Comment by dakyskye** [comment]
It should be fixed now!

**Comment by danielcherubini** [comment]
works perfectly.. thanks

**Comment by dakyskye** [comment]
Good to hear, happily closing the issue.
