### ISSUE TITLE
dxhd's spawned child processes become zombies

### ISSUE THREAD

**Issue by danielcherubini** [dakyskye/dxhd#14]
![image](https://user-images.githubusercontent.com/399473/84690950-9a065f80-af43-11ea-9a7c-aa1b09f1b9de.png)

Take a look at this, every time i use a keybind, i get one of these children processes. They don't seem to remove themselves.

Using the latest git version.

**Comment by dakyskye** [comment]
Oh, so dxhd does spawn Zombie processes. That's bad. Thanks for reporting! I will fix this.

**Comment by dakyskye** [comment]
They should get killed when you kill dxhd though.  However, I'll figure this out, I don't want users to have lots of zombie processes.

**Comment by dakyskye** [comment]
Fix: `Run` processes as goroutines, and pass them top-level context, to stop the process on context.Done()

**Comment by dakyskye** [comment]
That's fixed by the latest release.
