### ISSUE TITLE
a flag to launch dxhd in the background

### ISSUE THREAD

**Issue by dakyskye** [dakyskye/dxhd#28]
## What do you want

A flag (`-b` and `--background`) to start dxhd in the background (so, self-daemonise)

## Why

Because I sometimes kill dxhd instance(s) and would prefer if I could simply `dxhd -c path -b` over `dxhd -c path & disown`

**Comment by NotUnlikeTheWaves** [comment]
One way I've seen this is running `exec.Command(os.Args[0], os.Args[1:])` taking care to remove the -b flag

Alternatively (and more Linux-y) the `fork` syscall could be of use here where we can check if the PID from `os.Getpid()` is non-zero (i.e. it's a forked process)

**Comment by dakyskye** [comment]
We don't need to remove the `-b` flag.. just need to check it in `options.go`. And about "the alternative", there maybe is some way to tell system with `sys` package to make the self pid process disowned.

**Comment by dakyskye** [comment]
it's implemented in the master branch, not released yet.
