### ISSUE TITLE
Background flag is broken

### ISSUE THREAD

**Issue by NotUnlikeTheWaves** [dakyskye/dxhd#33]
## What happened

The `-b` flag doesn't work. `--background` doesn't either.

## How do you reproduce this bug

Fetch either dxhd-bin from the AUR or git clone and compile the master branch and run it with `dxhd -b` or `dxhd --background`

## Hints on what could have happened

No idea

## Information

| Key | Value |
| - | - |
| dxhd version | 30.10.2020_16.02 | 
| X server version | X.Org X Server 1.20.9        |

**Comment by dakyskye** [comment]
Haha, I accidentally kept `os.Exit`. Thanks for spotting the bug.
