### ISSUE TITLE
Automated testing suite

### ISSUE THREAD

**Issue by NotUnlikeTheWaves** [dakyskye/dxhd#35]
## What do you want

A test suite that tests behavior in dxhd such as the possible flags and possible keybindings.

A full integration test might be hard (but I want to check it out still) due to the X11 dependency. I do see a fun challenge in this though :) 

However, unit testing the config parser and flag parsing parts of the code should be very possible.

## Why

To not break exist code on new features or refactorings, as well as possibly being able to test against a specification on new feature requests, aka test driving development. It's also good in general to have a spec to test against rather than just documentation that 'should work'.

## Implementation hints

Will come back on this later, it's 1am.

**Comment by NotUnlikeTheWaves** [comment]
Also this could be a long lasting issue about unit/integration testing ideas in general, with perhaps follow-up issues for testing specific parts if necessary.

**Comment by dakyskye** [comment]
Yeah that's really really needed. Writing tests for the parser is pointless for now, because the parser code is very bad. However, we should use TDD worfklow for parser rewrite (I highlight parser has to be rewritten, it is way too bad that there's no fix for it).
