### ISSUE TITLE
Document the ability to run multiple instances simultaneously

### ISSUE THREAD

**Issue by avahe-kellenberger** [dakyskye/dxhd#40]
## What do you want

I'd like to logically separate my keybindings, based on what they are associated with.

I wasn't aware that I could run multiple instances of dxhd to use multiple configs at the same time, until I tried it.

## Why

Documentation is good, and this is a great feature.

## Implementation hints

Maybe put it in the README, and/or a wiki page.

**Comment by dakyskye** [comment]
:+1: good one. Never thought of mentioning it actually. I'll document it in the readme.
