### ISSUE TITLE
F13-24 keys not working

### ISSUE THREAD

**Issue by papojari** [dakyskye/dxhd#45]
## What do you want

My F13-24 keys are not working dxhd. This: 
`WARN can not register a keybinding                 error="Could not find a valid keycode in the string 'F13'. Key binding failed." keybinding="F13"` 
is what i get when i try to implement the F13 key in the dxdh.sh like this:

`## toggle mute`
`#F13` 
`<command>` 
and then launch dxhd.

## Why

This feature would add support for more keys and key combination which should be a good thing.

## Implementation hints

i don't have any experience with Go or Rust.

**Comment by dakyskye** [comment]
The X library dxhd uses is unmaintained and seems to have bugs that make development process unenjoyable and stuff unachievable. I'll look into what I can do about this when I get home. Rust rewrite must fix everything.

**Comment by dakyskye** [comment]
Hm, it does not make sense why F13 would not work. It is defined [here](https://github.com/BurntSushi/xgbutil/blob/master/keybind/keysymdef.go#L201) and should be working just fine.

Have you tried combining it with a modifier key, such as, super? Also, does `F12` for example work? I do not have a system with Xorg around so I can not test it myself, which I am sorry for.

**Comment by papojari** [comment]
I've done some more testing. F1-F12 works perfectly fine alone, with modifiers and with keys. F13-F24 only works with other keys. They are not recognized alone or with modifiers.

**Comment by dakyskye** [comment]
Ah, okay. I think that is Xorg related then. As far as I know Xorg does not accept all keys without modifiers. Or that might be what I've seen of using XGB (the X library dxhd uses). I hope Rust rewrite will satisfy everything we are missing now.

**Comment by dakyskye** [comment]
What I can say about this is that F13 and above are usually not buttons on keyboards nowadays, hence it must be why XGB does not accept them without a specifier. I hope that makes sense, though it's sad some keys (other  than those) can not be registered without a specifier(s).

**Comment by dakyskye** [comment]
sxhkd:
![image](https://user-images.githubusercontent.com/32128756/113522672-9b2c7a00-95b3-11eb-83b2-dd28d137743c.png)
